"""add file_type language mode input_type columns

Revision ID: c1db730b1956
Revises: 
Create Date: 2026-03-04 23:27:27.047453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1db730b1956'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('input_type', sa.String(length=10), nullable=True))

    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdfs', schema=None) as batch_op:
        batch_op.drop_column('file_type')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('input_type')
        batch_op.drop_column('mode')
        batch_op.drop_column('language')

    # ### end Alembic commands ###
